source "https://rubygems.org"

# Heroku uses the ruby version to configure your application's runtime.
ruby "2.2.2"

# Rails
gem "rails", "~> 4.1.0"

# Database drivers
gem "pg"

# Background worker
gem "que"

# Web server
gem "unicorn"

# Rack middleware
gem "rack-canonical-host"
gem "tzinfo-data"

# App
gem "adequate_exposure"
gem "interactor"
gem "kaminari"
gem "responders"
gem "eventmachine", "~>1.0.4"
gem "railties"
gem 'acts-as-taggable-on', '~> 3.4'
gem 'jquery-rails'
gem 'turbolinks'

# Login
gem "devise"
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem "omniauth-google-oauth2"

# Views
gem "jbuilder", "~> 2.0"
gem 'slim'
gem "slim-rails"
gem 'paperclip', '~> 4.2.2'
gem 'jquery-fileupload-rails' 
gem 'jquery-turbolinks'

# Integrations
gem "bugsnag"
gem "actionpack"
gem "activesupport"
gem "rspec-core"
gem "rspec-mocks"
gem "rspec-expectations"

# Frontend
gem "autoprefixer-rails"
gem "coffee-rails", "~> 4.0.0"
gem "meta-tags"
gem "react-rails"
gem "redcarpet"
gem "sass-rails", "~> 4.0.2"
gem "uglifier", ">= 1.3.0"
gem 'simple_form'
gem 'rails_admin', '~> 0.6.7'
gem 'friendly_id', '~> 5.1.0'

# Rails assets
# gem 'jquery-ui-rails', '~> 5.0.5'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.15.35'

group :production, :test do
  gem 'aws-sdk', '~> 1.6'
  gem "rails_12factor"
end

group :test do
  gem "capybara" # RSpec 3 deprecations, waiting for the next gem release.
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "fuubar", "~> 2.0.0"
  gem "poltergeist"
  gem "minitest" # Remove this after https://github.com/thoughtbot/shoulda-matchers/issues/408 is fixed.
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "simplecov", "~> 0.7.1" # https://github.com/colszowka/simplecov/issues/281
end

group :test, :development do
  gem "dotenv-rails"
  gem "rspec-rails", "~> 3.0.0.beta2"
end

# Development tools
group :development do
  gem 'rails_best_practices'
  gem "better_errors"
  gem "binding_of_caller"
  gem "foreman"
  gem "launchy"
  gem "quiet_assets"
  gem "spring"
  gem "spring-commands-rspec"
  # Guard et al
  gem "guard", "~> 2"
  gem "guard-rspec"
  gem "guard-livereload"
  gem "meta_request"
  # a gem for debugging
  gem 'byebug', '3.4.0'
end

# Mac-specific development tools
group :darwin do
  gem "rb-fsevent"
end
